### ISSUE TITLE
TypeError: 'newline' is an invalid keyword argument for this function in python3 

### ISSUE THREAD

**Issue by shakil-anwar** [wokwi/kicad-jlcpcb-bom-plugin#10]
sol:
Had to rewrite line 29
open(sys.argv[2], 'w', newline ='') as f: 
to:
open(sys.argv[2], 'wb') as f:

**Comment by urish** [comment]
It is valid in Python 3, according to docs: https://docs.python.org/3/library/functions.html#open

**Comment by jbuszkie** [comment]
I just got this too!
`Command error. Return code 1
Error messages:
Traceback (most recent call last):
  File "C:\Program Files\KiCad\bin\scripting\plugins/bom_csv_jlcpcb.py", line 29, in <module>
    with open(sys.argv[2], 'w', newline='') as f:
TypeError: 'newline' is an invalid keyword argument for this function`

I have python 3.9 installed..

**Comment by jbuszkie** [comment]
Update...  It seems like Kicad is using a different python version.  I had thought I uninstalled all 2.x versions...  Does Kicad have it's own python install?  Anyway..  If I run the script from Kicad I get this error...  If I run it from a command line then I don't get this error....  ( I get a different error like in one of the other open issues..  But that's a different issue..)
