### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by AiyionPrime** [wokwi/kicad-jlcpcb-bom-plugin#2]
Python3 compatibility would be rather nice :)

**Comment by urish** [comment]
a PR would be appreciated!

**Comment by AiyionPrime** [comment]
A pr was unlikely, as I found a different plugin, and is now likely again, as the other on did not work.
Maybe I'll get to this in the next week.

**Comment by urish** [comment]
Have you had a chance to look into it? I believe the changes needed are pretty minor

**Comment by AiyionPrime** [comment]
They surely are, but I haven't found the time yet.
Wont fix until I need it in a few days?, when my shipment from china arrives, sorry.

**Comment by urish** [comment]
No rush, in a few days is fine :)

**Comment by MarcelKr** [comment]
The fix is simple. See #3
