### ISSUE TITLE
No module named 'kicad_netlist_reader'

### ISSUE THREAD

**Issue by HansAchterbahn** [wokwi/kicad-jlcpcb-bom-plugin#5]
Hi, thanks for your work! Unfortunately, I get an error message when I try to execute the script in Eeschema. What is kicad_netlist_reader and how do I get it?

Greetings 
h8

__Command:__
```bash
python "/usr/share/kicad/scripting/plugins/bom_csv_jlcpcb.py" "%I" "%O"
```

__Error:__
```bash
Run command:
python "/usr/share/kicad/scripting/plugins/bom_csv_jlcpcb.py" "/home/hesse/Dokumente/KiCad/Projekte/Privat/MateLightScrewCap/MateLightScrewCap.xml" "/home/hesse/Dokumente/KiCad/Projekte/Privat/MateLightScrewCap/MateLightScrewCap.csv"

Command error. Return code 1
Error messages:
Traceback (most recent call last):
  File "/usr/share/kicad/scripting/plugins/bom_csv_jlcpcb.py", line 23, in <module>
    import kicad_netlist_reader
ModuleNotFoundError: No module named 'kicad_netlist_reader'
```

**Comment by urish** [comment]
Hi, it's part of KiCad. If for some reason your version doesn't include this file, you can get it from [their repo](https://github.com/KiCad/kicad-source-mirror/tree/master/eeschema/plugins/python_scripts)

**Comment by peterjc** [comment]
They moved it slightly, now at https://github.com/KiCad/kicad-source-mirror/blob/master/eeschema/python_scripts/kicad_netlist_reader.py
