### ISSUE TITLE
ModuleNotFoundError: No module named ‘kicad_netlist_reader’

### ISSUE THREAD

**Issue by EdwardChamberlain** [wokwi/kicad-jlcpcb-bom-plugin#6]
When running the BOM script I get the error:
```
Command error. Return code 1
Error messages:
Traceback (most recent call last):
  File “/private/var/folders/4r/0wdgxsd94j5bq4nywh48q9bh0000gn/T/AppTranslocation/7B6115DA-01DD-4A95-BA1E-A6283AC1F807/d/kicad.app/Contents/SharedSupport/scripting/bom_csv_jlcpcb.py”, line 23, in <module>
    import kicad_netlist_reader
ModuleNotFoundError: No module named ‘kicad_netlist_reader’
```

I have tried installing this module with pip but to no avail. I can import the module in a python session. 

Platform: macOS
KiCAD: 5.1.9
Python: 3.9.0

**Comment by Joe-Lannan** [comment]
Had this issue on windows 11, fixed by copying the kicad_netlist_reader.py from C:\Program Files\KiCad\7.0\bin\scripting\plugins to the same location as the script.

**Comment by peterjc** [comment]
Duplicate of #5.
